
services:
  server:
    image: progetto_lso_server
    build:
      context: ./server  
      dockerfile: dockerfile  
    container_name: myserver
    ports:
      - "10000:10000"
    networks:
      - tris-network
    command: ./server  

  client:
    image: progetto_lso_client
    build:
      context: ./client  
      dockerfile: dockerfile  
    container_name: tris-client
    networks:
      - tris-network
    depends_on:
      - server
    command: ./client  

networks:
  tris-network:
    driver: bridge

# Dockerfile for server // --> docker compose up server    
# Dockerfile for client // --> docker compose run --rm client  poi ./client