FROM alpine:latest

WORKDIR /app


RUN apk update && \
    apk add --no-cache gcc libc-dev


COPY . /app/


RUN gcc -c server.c -o server.o && \
    gcc -c source_file/connessione.c -o connessione.o && \
    gcc -c source_file/impl_server.c -o impl_server.o && \
    gcc -c source_file/gestisci_giocatore.c -o gestisci_giocatore.o && \
    gcc -c source_file/gestisci_partite.c -o gestisci_partite.o && \
    gcc -o server server.o connessione.o impl_server.o gestisci_giocatore.o gestisci_partite.o 


EXPOSE 10000


CMD ["./server"]
